# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  ImageName: 'adityaranjansharma/frontend'  

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    # - task: Docker@2
    #   displayName: Build an image
    #   inputs:
    #     command: build
    #     repository: '$(ImageName)'
    #     dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    #     tags: $(tag)
    # - task: Docker@2
    #   inputs:
    #     containerRegistry: 'DockerHub'
    #     repository: 'adityaranjansharma/frontend'
    #     command: 'push'
    - script: |
        # cd elastic-beanstalk
        zip -r output.zip ./*
      displayName: 'install, build and zip'
    - task: S3Upload@1
      inputs:
        awsCredentials: 'aws-connection'
        regionName: 'us-east-1'
        bucketName: 'elasticbeanstalk-us-east-1-280853110689'
        # globExpressions: '**'
        globExpressions: output.zip
    - task: BeanstalkDeployApplication@1
      inputs:
        awsCredentials: 'aws-connection'
        regionName: 'us-east-1'
        applicationName: 'docker-react'
        environmentName: 'Dockerreact-env'
        applicationType: s3
        deploymentBundleBucket: elasticbeanstalk-us-east-1-280853110689
        deploymentBundleKey: output.zip
        logRequest: true
        logResponse: true
        versionLabel: 'Sample Application 10'
        
