# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  ImageName: 'adityaranjansharma/frontend'  

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        repository: '$(ImageName)'
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile.dev'
        tags: $(tag)
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub'
        repository: 'adityaranjansharma/frontend'
        command: 'push'
    - task: S3Upload@1
      displayName: 'S3 Upload: angular-docker-bucket'
      inputs:
        awsCredentials: 'aws-connection'
        regionName: 'us-east-1'
        bucketName: 'elasticbeanstalk-us-east-1-280853110689'
        sourceFolder: ''
        globExpressions: output.zip
        createBucket: true
    - task: BeanstalkDeployApplication@1
      inputs:
        awsCredentials: 'aws-connection'
        regionName: 'us-east-1'
        applicationName: 'docker-react'
        environmentName: 'Dockerreact-env'
        applicationType: 'version'
        deploymentBundleBucket: elasticbeanstalk-us-east-1-280853110689
        deploymentBundleKey: output.zip
        logRequest: true
        logResponse: true
        versionLabel: '3'